# serverless.yml

service: expressApp

custom :
  tableName : user-table-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    USERS_TABLE: ${self:custom.tableName} 

functions:
  app:
    handler: index.handler
    events:
     - http:
        path: /
        method: GET
     - http:
        path: /user
        method: GET 
     - http:
        path: /user 
        method: POST 

resources:
  Resources:
    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


