# serverless.yml

service: expressApp

custom :
  tableName : users-table-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb: Query
       - dynamodb: Scan
       - dynamodb: GetItem
       - dynamodb: PutItem
       - dynamodb: UpdateItem
       - dynamodb: DeleteItem
      Resource: 
        - { "Fn::GetAtt" : ["UsersDynamoDBTable","Arn"] }
  environment:
    USERS_TABLE: ${self:custom.tableName} 

functions:
  app:
    handler: index.handler
    events:
     - http:
        path: /
        method: GET
     - http:
        path: /user
        method: GET 
     - http:
        path: /user 
        method: POST 

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - 
            AttributeName: emailID
            AttributeType: S
        
        KeySchema:
          -
            AttributeName: emailID
            KeyType: HASH
        
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        
        TableName : ${self:custom.tableName}


